### ISSUE TITLE
DNR lists are still set to work after disabling all 3 features (Ad-Blocking, Anti-Tracking, Never-Consent)

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1625]
**Description**
DNR lists are still set to works, even if all 3 features (Ad-Blocking, Anti-Tracking, Never-Consent) are disabled. 

**Steps to Reproduce**

1. Open Ghostery settings, click 3 times on the version number to open dev tools
2. Disable all 3 features (Ad-Blocking, Anti-Tracking, Never-Consent)
3. Open any other tab, for example Websites, and go back to Privacy protection tab
4. Open dev tools once more
5. Look at DNR rulesets
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/db5f04d6-a46c-4087-823b-1e5cbe51609a)

6. Open any website, for example https://aarp.org and open Ghostery panel
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/d49f3354-d577-417e-9e3f-b0d14b69221e)

**Expected results:**
When all 3 features (Ad-Blocking, Anti-Tracking, Never-Consent) are disabled, it should work just like Pause. Nothing should be blocked.

**Versions:**
```
Browser: Safari 17.5
OS: MacOS 14.5
GBE 10.3.4

Browser: Safari
OS: iOS 17.5.1
GBE 10.3.4

Browser: Edge 125.0.2535.79
OS: Windows 10
GBE 10.3.4
```

**Comment by GRadziejewski** [comment]
Fixed. Checked on 10.3.5. 
On Edge:
![image](https://github.com/ghostery/ghostery-extension/assets/40433708/698a2bd5-eb3b-4cad-8f6b-fec849c62f82)

**Comment by nikau6** [comment]
Not fixed for me. I'm on Fedora 42 using Vivaldi and even after I disabled all of the Ghostery settings it's still working

**Comment by smalluban** [comment]
The issue concerns DNR rules, and I can confirm that either pausing Ghostery or disabling all main features disables them and clears the list of enabled DNR lists. 

@nikau6 If you open DevTools (click five times on the version number in the settings page), you can check the currently enabled DNR lists.

If you mean blocking ads, etc, it might relate to cosmetic filters, but adblocker engine is disabled as well.
