### ISSUE TITLE
Images on Google My Maps are not loading

### ISSUE THREAD

**Issue by kospl** [ghostery/ghostery-extension#578]
### Description

When Ghostery activated, images on custom Google My Maps are not loaded because of HTTP 400 error.

Network debugger shows next redirects:
`https://doc-08-ao-mymaps.googleusercontent.com/untrusted/hostedimage/67ht0gn364521qiheeia79564g/bdrpki2n3r44tr21p85bik0o6s/1593856800000/N-EfLdaSoKzXTNQ73EyhZJIKbix9rfOj/*/6AF2TALoEion93iHNuEQPr5ZAO-GVoe6nSSBlrS0i2YCpnDVEaalIlBXqy9pitWRrxicbcnO3X547lquQPlesWPoMZuuLNAzKTXDIhREtFfAsAnb46kmospSZ4aoqaAEGF0z2hMAHZIm_2flUsS7xhPcjqYLq24c5SeRDFtXfOd1LcXN7eMAE_D0Zgjxzuo834amAHW0J6ub9jMSeLIaSy0IOBCoBToOb_xom2FiGNTSUQ4in50ANfltQ-G7jjWig0ey04r27QGM4ngoHLKdYe6afZx4durvoqg?fife=s16383` - **`Status Code: 307 Internal Redirect`**

`https://doc-08-ao-mymaps.googleusercontent.com/untrusted/hostedimage/67ht0gn364521qiheeia79564g/bdrpki2n3r44tr21p85bik0o6s/1593856800000/N-EfLdaSoKzXTNQ73EyhZJIKbix9rfOj/*/6AF2TALoEion93iHNuEQPr5ZAO-GVoe6nSSBlrS0i2YCpnDVEaalIlBXqy9pitWRrxicbcnO3X547lquQPlesWPoMZuuLNAzKTXDIhREtFfAsAnb46kmospSZ4aoqaAEGF0z2hMAHZIm_2flUsS7xhPcjqYLq24c5SeRDFtXfOd1LcXN7eMAE_D0Zgjxzuo834amAHW0J6ub9jMSeLIaSy0IOBCoBToOb_xom2FiGNTSUQ4in50ANfltQ-G7jjWig0ey04r27QGM4ngoHLKdYe6afZx4durvoqg?fife=ghostery` - **`Status Code: 400`**

Note: `?fife=ghostery` appears in URL of broken image.

When Ghostery disabled, all images are opened with `Status Code: 200`.

### Expected Behavior

When open sample Google My Map you can click on lines with photos attached, and view the photos.

### Actual Behavior
When clicking on attached photo, it's not loaded.

### Steps to Reproduce

1. Open https://www.google.com/maps/d/viewer?mid=1K_nUMrLDGwqVm79pghRSmdRLdLyDl3xV&ll=48.46006013730118%2C35.07753903903811&z=14
2. Click on line with photos attached
![image](https://user-images.githubusercontent.com/26386660/86510311-4cb93780-bdf7-11ea-9fe3-8ce9a2d84154.png)
3. Click on photos.
4. See "broken image" icon instead of actual photo.
![image](https://user-images.githubusercontent.com/26386660/86510248-c69cf100-bdf6-11ea-81dd-d424c4dfeaad.png)

### Versions

+ Browser: Chrome 83.0.4103.116
+ OS: Windows 10
+ Node: -
+ NPM: -

**Comment by christophertino** [comment]
Thanks for reporting. We've identified the issue and pushed an update to our anti-tracking lists. You should see this resolved in the next 24hrs.

**Comment by kospl** [comment]
Checked, it still fails loading the images after repeating "Steps to Reproduce".

**Comment by christophertino** [comment]
The images appear to be loading fine for me now on FF and Chrome.  I see `&fife=s16383` in the image path and a 200 response.

**Comment by kospl** [comment]
@christophertino yes, now it's working, thanks!
